/**
 * CompoundViewer3D — Research-grade 3D molecular viewer.
 *
 * Uses 3Dmol.js with SDF format for explicit bond rendering.
 * Inspired by PDB protein viewers — large spheres, thick sticks,
 * dark gradient background, smooth spinning, and view mode toggle.
 */
import { useEffect, useRef, useCallback, useState } from "react";

interface Atom {
    id: number;
    symbol: string;
    x: number;
    y: number;
    z: number;
    radius: number;
    color: string;
}

interface Bond {
    from: number;
    to: number;
}

interface CompoundStructure {
    atoms: Atom[];
    bonds: Bond[];
    total_atoms: number;
}

type ViewMode = "ball-stick" | "spacefill" | "stick" | "cartoon";

interface CompoundViewer3DProps {
    structure: CompoundStructure;
    height?: string;
    showLabels?: boolean;
    className?: string;
    compoundName?: string;
}

// Load 3Dmol.js from CDN once
let scriptLoaded = false;
let scriptPromise: Promise<void> | null = null;

function load3Dmol(): Promise<void> {
    if (scriptLoaded && (window as any).$3Dmol) return Promise.resolve();
    if (scriptPromise) return scriptPromise;

    scriptPromise = new Promise((resolve, reject) => {
        if ((window as any).$3Dmol) {
            scriptLoaded = true;
            resolve();
            return;
        }
        const script = document.createElement("script");
        script.src = "https://3Dmol.org/build/3Dmol-min.js";
        script.onload = () => {
            scriptLoaded = true;
            resolve();
        };
        script.onerror = () => reject(new Error("Failed to load 3Dmol.js"));
        document.head.appendChild(script);
    });

    return scriptPromise;
}

/**
 * Convert our backend structure to SDF (MOL V2000) format.
 */
function structureToSDF(structure: CompoundStructure): string {
    const { atoms, bonds } = structure;
    const lines: string[] = [];

    lines.push("CompoundViewer");
    lines.push("  QuantumMD   3D");
    lines.push("Generated by QuantumMaterialDiscovery");

    const nAtoms = String(atoms.length).padStart(3);
    const nBonds = String(bonds.length).padStart(3);
    lines.push(`${nAtoms}${nBonds}  0  0  0  0  0  0  0  0999 V2000`);

    for (const atom of atoms) {
        const x = atom.x.toFixed(4).padStart(10);
        const y = atom.y.toFixed(4).padStart(10);
        const z = atom.z.toFixed(4).padStart(10);
        const sym = ` ${atom.symbol.padEnd(3)}`;
        lines.push(`${x}${y}${z}${sym} 0  0  0  0  0  0  0  0  0  0  0  0`);
    }

    for (const bond of bonds) {
        const a1 = String(bond.from + 1).padStart(3);
        const a2 = String(bond.to + 1).padStart(3);
        const bo = "  1";
        lines.push(`${a1}${a2}${bo}  0  0  0  0`);
    }

    lines.push("M  END");
    lines.push("$$$$");
    return lines.join("\n");
}

export function CompoundViewer3D({
    structure,
    height = "320px",
    showLabels = true,
    className = "",
    compoundName,
}: CompoundViewer3DProps) {
    const containerRef = useRef<HTMLDivElement>(null);
    const viewerRef = useRef<any>(null);
    const [viewMode, setViewMode] = useState<ViewMode>("ball-stick");

    const applyStyle = useCallback((viewer: any, mode: ViewMode) => {
        if (!viewer || !structure) return;

        viewer.setStyle({}, {}); // Clear styles

        switch (mode) {
            case "ball-stick":
                viewer.setStyle({}, {
                    stick: {
                        radius: 0.18,
                        colorscheme: "Jmol",
                    },
                    sphere: {
                        scale: 0.45,
                        colorscheme: "Jmol",
                    },
                });
                break;
            case "spacefill":
                viewer.setStyle({}, {
                    sphere: {
                        scale: 0.85,
                        colorscheme: "Jmol",
                    },
                });
                break;
            case "stick":
                viewer.setStyle({}, {
                    stick: {
                        radius: 0.22,
                        colorscheme: "Jmol",
                    },
                });
                break;
            case "cartoon":
                viewer.setStyle({}, {
                    stick: {
                        radius: 0.12,
                        colorscheme: "Jmol",
                    },
                    sphere: {
                        scale: 0.3,
                        colorscheme: "Jmol",
                    },
                });
                break;
        }

        // Override colors with our backend CPK colors for richer appearance
        structure.atoms.forEach((atom, i) => {
            if (atom.color) {
                const hexColor = parseInt(atom.color.replace("#", "0x"), 16);
                const currentMode = mode;
                const styles: any = {};
                if (currentMode === "ball-stick" || currentMode === "cartoon") {
                    styles.stick = {
                        radius: currentMode === "ball-stick" ? 0.18 : 0.12,
                        color: hexColor,
                    };
                    styles.sphere = {
                        scale: currentMode === "ball-stick" ? 0.45 : 0.3,
                        color: hexColor,
                    };
                } else if (currentMode === "spacefill") {
                    styles.sphere = { scale: 0.85, color: hexColor };
                } else if (currentMode === "stick") {
                    styles.stick = { radius: 0.22, color: hexColor };
                }
                viewer.setStyle({ index: i }, styles);
            }
        });

        viewer.render();
    }, [structure]);

    const initViewer = useCallback(async () => {
        if (!containerRef.current || !structure || structure.atoms.length === 0) return;

        try {
            await load3Dmol();
        } catch {
            console.error("Could not load 3Dmol.js");
            return;
        }

        const $3Dmol = (window as any).$3Dmol;
        if (!$3Dmol) return;

        if (viewerRef.current) {
            try { viewerRef.current.clear(); } catch { }
        }
        containerRef.current.innerHTML = "";

        const viewer = $3Dmol.createViewer(containerRef.current, {
            backgroundColor: "0x0a0f1e",
            antialias: true,
        });
        viewerRef.current = viewer;

        const sdf = structureToSDF(structure);
        viewer.addModel(sdf, "sdf");

        applyStyle(viewer, viewMode);

        // Labels with glassmorphism
        if (showLabels) {
            structure.atoms.forEach((atom) => {
                viewer.addLabel(atom.symbol, {
                    position: { x: atom.x, y: atom.y, z: atom.z },
                    fontSize: 11,
                    fontColor: "white",
                    fontOpacity: 0.95,
                    backgroundColor: "0x0f172a",
                    backgroundOpacity: 0.75,
                    borderColor: atom.color || "0x64748b",
                    borderThickness: 1.5,
                    showBackground: true,
                    alignment: "center",
                    inFront: true,
                });
            });
        }

        viewer.zoomTo();
        viewer.zoom(0.85);
        viewer.spin("y", 0.6);
        viewer.render();
    }, [structure, showLabels, viewMode, applyStyle]);

    useEffect(() => {
        initViewer();
        return () => {
            if (viewerRef.current) {
                try { viewerRef.current.clear(); } catch { }
                viewerRef.current = null;
            }
        };
    }, [initViewer]);

    // Re-apply style when viewMode changes without full re-init
    useEffect(() => {
        if (viewerRef.current) {
            applyStyle(viewerRef.current, viewMode);
        }
    }, [viewMode, applyStyle]);

    if (!structure || structure.atoms.length === 0) {
        return (
            <div
                className={`flex items-center justify-center bg-muted/20 rounded-lg border border-border/50 ${className}`}
                style={{ height }}
            >
                <p className="text-sm text-muted-foreground">No structure data</p>
            </div>
        );
    }

    const viewModes: { key: ViewMode; label: string }[] = [
        { key: "ball-stick", label: "Ball & Stick" },
        { key: "spacefill", label: "Spacefill" },
        { key: "stick", label: "Stick" },
    ];

    return (
        <div
            className={`relative rounded-xl overflow-hidden ${className}`}
            style={{
                height,
                background: "linear-gradient(135deg, #0a0f1e 0%, #111827 40%, #1a1f2e 100%)",
                border: "1px solid rgba(99, 102, 241, 0.2)",
                boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255,255,255,0.05)",
            }}
        >
            <div ref={containerRef} style={{ width: "100%", height: "100%" }} />

            {/* View mode toggle - top left */}
            <div className="absolute top-2 left-2 flex gap-1 bg-black/60 backdrop-blur-sm rounded-lg p-1 border border-white/10">
                {viewModes.map((m) => (
                    <button
                        key={m.key}
                        onClick={() => setViewMode(m.key)}
                        className={`px-2.5 py-1 rounded-md text-[10px] font-medium transition-all ${viewMode === m.key
                                ? "bg-indigo-500/80 text-white shadow-sm"
                                : "text-slate-400 hover:text-white hover:bg-white/10"
                            }`}
                    >
                        {m.label}
                    </button>
                ))}
            </div>

            {/* Compound info - bottom left */}
            <div className="absolute bottom-2 left-2 px-3 py-1.5 rounded-lg bg-black/60 backdrop-blur-sm border border-white/10 flex items-center gap-3 pointer-events-none">
                <span className="text-[10px] text-cyan-400 font-mono font-bold">
                    🧪 {structure.total_atoms} atoms
                </span>
                <span className="text-[10px] text-slate-500">•</span>
                <span className="text-[10px] text-indigo-400 font-mono">
                    {structure.bonds.length} bonds
                </span>
                {compoundName && (
                    <>
                        <span className="text-[10px] text-slate-500">•</span>
                        <span className="text-[10px] text-emerald-400 font-medium">
                            {compoundName}
                        </span>
                    </>
                )}
            </div>

            {/* Controls hint - bottom right */}
            <div className="absolute bottom-2 right-2 px-2.5 py-1 rounded-lg bg-black/40 backdrop-blur-sm text-[9px] text-slate-500 pointer-events-none border border-white/5">
                Rotate: drag · Zoom: scroll · Pan: right-drag
            </div>
        </div>
    );
}

export default CompoundViewer3D;
